$baseUrl = "https://eduprosuite-org.github.io/study/"
$date = Get-Date -Format "yyyy-MM-dd"

# 1. Pages (Root)
$urlsPages = @("")

# 2. Exams
$urlsExams = @(
    "exams/ca-real-estate-math/"
    "exams/ca-real-estate-math/practice.html"
    "exams/plumbing-aptitude-test/"
    "exams/plumbing-aptitude-test/practice-test/"
    "exams/plumbing-aptitude-test/study-guide/"
    "exams/sarasota-adu-permit-checklist/"
    "exams/gwinnett-home-occupation-checklist/"
    "exams/douglas-co-residential-building-checklist/"
    "exams/vic-lea-electrician-prep/"
    "exams/plumbing-license-prep/"
    "exams/plumbing-license-prep/journeyman/"
    "exams/plumbing-license-prep/master-contractor/"
    "exams/plumbing-license-prep/tradesman-other/"
    "exams/plumbing-license-prep/general/"
    "exams/plumbing-license-prep/journeyman/general-prep/"
    "exams/plumbing-license-prep/journeyman/general-prep/practice.html"
    "exams/plumbing-license-prep/journeyman/texas-prep/"
    "exams/plumbing-license-prep/journeyman/texas-prep/practice.html"
    "exams/plumbing-license-prep/journeyman/va-prep/"
    "exams/plumbing-license-prep/journeyman/va-prep/practice.html"
    "exams/plumbing-license-prep/journeyman/kansas-prep/"
    "exams/plumbing-license-prep/journeyman/kansas-prep/practice.html"
    "exams/plumbing-license-prep/journeyman/ma-prep/"
    "exams/plumbing-license-prep/journeyman/ma-prep/practice.html"
    "exams/plumbing-license-prep/journeyman/wssc-prep/"
    "exams/plumbing-license-prep/journeyman/wssc-prep/practice.html"
    "exams/plumbing-license-prep/master-contractor/master-prep/"
    "exams/plumbing-license-prep/master-contractor/master-prep/practice.html"
    "exams/plumbing-license-prep/master-contractor/contractor-prep/"
    "exams/plumbing-license-prep/master-contractor/contractor-prep/practice.html"
    "exams/plumbing-license-prep/tradesman-other/tradesman-prep/"
    "exams/plumbing-license-prep/tradesman-other/tradesman-prep/practice.html"
    "exams/plumbing-license-prep/tradesman-other/inspector-prep/"
    "exams/plumbing-license-prep/tradesman-other/inspector-prep/practice.html"
    "exams/plumbing-license-prep/general/residential-prep/"
    "exams/plumbing-license-prep/general/residential-prep/practice.html"
    "exams/plumbing-license-prep/general/code-cert-prep/"
    "exams/plumbing-license-prep/general/code-cert-prep/practice.html"
    "exams/plumbing-license-prep/general/free-prep/"
    "exams/plumbing-license-prep/general/free-prep/practice.html"
)

# 3. Wiki
$urlsWiki = @(
    "wiki/"
    "wiki/plumbing-aptitude/"
    "wiki/plumbing-aptitude/how-to-pass-plumbing-aptitude-test/"
    "wiki/plumbing/air-gap/"
    "wiki/plumbing/air-chamber/"
    "wiki/plumbing/angle-valve/"
    "wiki/plumbing/fixture-clearances-accessibility-rules/"
    "wiki/plumbing/accumulator/"
    "wiki/plumbing/aerator/"
    "wiki/plumbing/area-drain/"
    "wiki/plumbing/backflow/"
    "wiki/plumbing/backflow-preventer/"
    "wiki/plumbing/backwater-valve/"
    "wiki/plumbing/ball-valve/"
    "wiki/plumbing/bidet/"
    "wiki/plumbing/blackwater/"
    "wiki/plumbing/branch/"
    "wiki/plumbing/branch-interval/"
    "wiki/plumbing/building-drain/"
    "wiki/plumbing/building-sewer/"
    "wiki/plumbing/cleanout-access-points/"
    "wiki/plumbing/common-venting-rules/"
    "wiki/plumbing/cistern/"
    "wiki/plumbing/cesspool/"
    "wiki/plumbing/coupling/"
    "wiki/plumbing/cross-connection/"
    "wiki/plumbing/crown-venting/"
    "wiki/plumbing/dead-end/"
    "wiki/plumbing/developed-length/"
    "wiki/plumbing/digestion/"
    "wiki/plumbing/double-check-valve/"
    "wiki/plumbing/downspout/"
    "wiki/plumbing/drain/"
    "wiki/plumbing/drainage-fixture-unit/"
    "wiki/plumbing/dry-vent/"
    "wiki/plumbing/elbow/"
    "wiki/plumbing/effluent/"
    "wiki/plumbing/ejector-pump/"
    "wiki/plumbing/escutcheon/"
    "wiki/plumbing/expansion-joint/"
    "wiki/plumbing/pipe-grade-slope-fall/"
    "wiki/plumbing/faucet/"
    "wiki/plumbing/fixture/"
    "wiki/plumbing/fixture-branch/"
    "wiki/plumbing/fixture-drain/"
    "wiki/plumbing/fixture-supply/"
    "wiki/plumbing/flood-level-rim/"
    "wiki/plumbing/flow-rate/"
    "wiki/plumbing/flush-valve/"
    "wiki/plumbing/flushometer/"
    "wiki/plumbing/gate-valve/"
    "wiki/plumbing/pipe-grade-slope-fall/"
    "wiki/plumbing/graywater/"
    "wiki/plumbing/grease-interceptor/"
    "wiki/plumbing/hanger/"
    "wiki/plumbing/horizontal-branch/"
    "wiki/plumbing/horizontal-pipe/"
    "wiki/plumbing/hot-water/"
    "wiki/plumbing/house-sewer/"
    "wiki/plumbing/indirect-waste/"
    "wiki/plumbing/individual-vent/"
    "wiki/plumbing/invert/"
    "wiki/plumbing/ipc/"
    "wiki/plumbing/ips/"
    "wiki/plumbing/designing-dwv-isometric-drawings/"
    "wiki/plumbing/journeyman-exam-requirements-and-format/"
    "wiki/plumbing/loop-vent/"
    "wiki/plumbing/master-vs-journeyman/"
    "wiki/plumbing/main/"
    "wiki/plumbing/manifold/"
    "wiki/plumbing/mechanical-joint/"
    "wiki/plumbing/nonpotable-water/"
    "wiki/plumbing/45-degree-rolling-offsets/"
    "wiki/plumbing/o-ring/"
    "wiki/plumbing/outfall/"
    "wiki/plumbing/p-trap/"
    "wiki/plumbing/pe-pipe/"
    "wiki/plumbing/pex-tubing/"
    "wiki/plumbing/plumb/"
    "wiki/plumbing/plumbing-appliance/"
    "wiki/plumbing/plumbing-appurtenance/"
    "wiki/plumbing/relief-valve/"
    "wiki/plumbing/rim/"
    "wiki/plumbing/45-degree-rolling-offsets/"
    "wiki/plumbing/riser/"
    "wiki/plumbing/45-degree-rolling-offsets/"
    "wiki/plumbing/rough-in/"
    "wiki/plumbing/pipe-grade-slope-fall/"
    "wiki/plumbing/saddle-valve/"
    "wiki/plumbing/sanitary-sewer/"
    "wiki/plumbing/siphonage/"
    "wiki/plumbing/pipe-grade-slope-fall/"
    "wiki/plumbing/soil-stack/"
    "wiki/plumbing/soil-pipe/"
    "wiki/plumbing/stack/"
    "wiki/plumbing/stack-vent/"
    "wiki/plumbing/storm-sewer/"
    "wiki/plumbing/sump/"
    "wiki/plumbing/tee-fitting/"
    "wiki/plumbing/tailpiece/"
    "wiki/plumbing/p-trap/"
    "wiki/plumbing/trap-arm/"
    "wiki/plumbing/trap-primer/"
    "wiki/plumbing/trap-seal/"
    "wiki/plumbing/upc/"
    "wiki/plumbing/union/"
    "wiki/plumbing/urinal/"
    "wiki/plumbing/vacuum-breaker/"
    "wiki/plumbing/valve/"
    "wiki/plumbing/sizing-vent-systems-ipc-upc/"
    "wiki/plumbing/vent-stack/"
    "wiki/plumbing/vertical-pipe/"
    "wiki/plumbing/blackwater/"
    "wiki/plumbing/waste-pipe/"
    "wiki/plumbing/water-closet/"
    "wiki/plumbing/water-main/"
    "wiki/plumbing/water-meter/"
    "wiki/plumbing/water-service-pipe/"
    "wiki/plumbing/sizing-vent-systems-ipc-upc/"
    "wiki/plumbing/sizing-water-distribution-pipe-systems/"
    "wiki/plumbing/wye-fitting/"
    "wiki/plumbing/yoke-vent/"
    "wiki/plumbing/fractions-decimals-basics/"
    "wiki/plumbing/gas-piping-venting-safety-standards/"
    "wiki/plumbing/reading-plumbing-blueprints-for-beginners/"
    "wiki/plumbing/how-to-tabs-highlight-codebooks-for-exam-speed/"
    "wiki/plumbing/deconstructing-journeyman-scenario-based-exam-questions/"
    "wiki/plumbing/history-of-plumbing-codes/"
)

function Generate-Sitemap($urls, $filename) {
    $xml = '<?xml version="1.0" encoding="UTF-8"?>' + "`n"
    $xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + "`n"
    
    foreach ($url in $urls) {
        $loc = $baseUrl + $url
        $priority = "0.8"
        if ($url -eq "") { $priority = "1.0" }
        elseif ($url.EndsWith("/")) { $priority = "0.9" }
        
        $xml += "    <url>`n"
        $xml += "        <loc>$loc</loc>`n"
        $xml += "        <lastmod>$date</lastmod>`n"
        $xml += "        <changefreq>weekly</changefreq>`n"
        $xml += "        <priority>$priority</priority>`n"
        $xml += "    </url>`n"
    }
    
    $xml += '</urlset>'
    
    $path = Join-Path $PSScriptRoot $filename
    [System.IO.File]::WriteAllText($path, $xml)
    Write-Host "$filename generated successfully!" -ForegroundColor Green
}

# Generate individual sitemaps
Generate-Sitemap -urls $urlsPages -filename "sitemap-pages.xml"
Generate-Sitemap -urls $urlsExams -filename "sitemap-exams.xml"
Generate-Sitemap -urls $urlsWiki -filename "sitemap-wiki.xml"

# Generate Sitemap Index
$sitemapIndexXml = '<?xml version="1.0" encoding="UTF-8"?>' + "`n"
$sitemapIndexXml += '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + "`n"

$sitemaps = @("sitemap-pages.xml", "sitemap-exams.xml", "sitemap-wiki.xml")
foreach ($sm in $sitemaps) {
    $loc = $baseUrl + $sm
    $sitemapIndexXml += "    <sitemap>`n"
    $sitemapIndexXml += "        <loc>$loc</loc>`n"
    $sitemapIndexXml += "        <lastmod>$date</lastmod>`n"
    $sitemapIndexXml += "    </sitemap>`n"
}
$sitemapIndexXml += '</sitemapindex>'

$indexPath = Join-Path $PSScriptRoot "sitemap.xml"
[System.IO.File]::WriteAllText($indexPath, $sitemapIndexXml)
Write-Host "sitemap.xml (Index) generated successfully!" -ForegroundColor Green



